version: "3.8"

services:
  yolo:
    image: yolo-ncnn-api
    container_name: yolo-ncnn
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8863:8863"
    restart: unless-stopped
    ipc: host